id = "catppuccin"
name = "Catppuccin Themes"
schema_version = 1
version = "0.2.6"
authors = ["Andrew Tec <andrewtec@enjoi.dev>"]
description = "tokyo"
repository = "https://github.com/catppuccin/zed"
